config/routes.rb
Politics::Application.routes.draw do
  get "home/index"

  resources :questions
  resources :parties
  resources :machings, :replace_id_with => 'access_token' do
    collection { post "result" }
    resources :answers
  end
  resources :answers
  root :to => 'home#index'
  get "android/new"
  match "/android", :controller => :android, :action => :index
  match "android/post", :controller => :android, :action => :post
  post "android/create", :controller => :android, :action => :create 
end

app/models/question.rb
# -*- coding: utf-8 -*-

class Question < ActiveRecord::Base

  belongs_to :answer, foreign_key: "question_id"
  has_many :party_answers
  has_many :questions, through: :party_answers, :uniq => true
  
  accepts_nested_attributes_for :party_answers

  attr_accessible(
    :question_content,
    :question_id,
    :question_description,
    :question_img,
    :answer_content,
    :party_answers_attributes
  )

  question_label = { question_con: "質問内容", opinion: "考え" }

end

app/controllers/questions_controller.rb
# -*- coding: utf-8 -*-
require 'open-uri'

class QuestionsController < ApplicationController

  def index
    url = request.host
    uuid = UUID.new.generate
    @questions = Question.find(:all, :order=>"question_id ASC")
    @question_content = Question.find(:all, :select=>"id, question_content, question_description, question_img", :order=>"question_id ASC")
    @question_content.each do |value|
      value[:question_img] = 'http://' + url + value[:question_img]
    end
    @hash = {questions: @question_content, uuid: uuid}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hash }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @question = Question.find(params[:id])
    @parties = Party.all
    @party_answers = PartyAnswer.find(:all, :select => "answer_content", :conditions => {:question_id => params[:id]})
    @edit_id = params[:id].to_i
  end


  def new
    @question = Question.new
    @party_answers = PartyAnswer.new
    @question.party_answers.build
    @parties = Party.all
  end

  # GET /questions/1/edit


  def create
    @question = Question.new(params[:question])
    @party = PartyAnswer.new(params[:party_answers])
  
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @questions.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @question = Question.find(params[:id])
    @question.party_answers.build
    @parties = Party.all
  end


  def update
    @question = Question.find(params[:id])
    @party_answer = @question.party_answers.find_all_by_question_id(params[:id])
    PartyAnswer.where(question_id: params[:id]).delete_all
    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/questions_helper.rb
# -*- coding: utf-8 -*-
module QuestionsHelper

  def question_answer_label(num)
    case num
      when 0
        p "反対"
      when 1
        p "賛成"
      when 2
        p "中立"
    end

  end

  def party_content_label(num)
    case num
      when 1
         "賛成"
      when 2
         "やや賛成"
      when 3
         "中立"
      when 4
         "やや反対"
      when 5
         "反対"
    end

  end


end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :質問内容 %><br />
      <%= f.text_field :question_content %><br />
      <%= f.label :質問説明 %><br />
      <%= f.text_area :question_description %><br />
      <%= f.label :質問番号 %><br />
      <%= f.text_field :question_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Questions</h1>

<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <%= f.label :質問内容 %><br />
      <%= f.text_field :question_content %><br />
      <% if @question[:question_img].present? %>
        <%= image_tag @question[:question_img] %>
      <% end %>
      <%= f.label :画像パス %><br />
      <%= f.text_field :question_img %><br />
      <%= f.label :説明 %><br />
      <%= f.text_area :question_description %><br />
      <%= f.label :質問番号 %><br />
      <%= f.text_field :question_id %>
  </div>

    <% @parties.each_with_index do |party, key| %>   
    <h3><%= party[:party_name] %></h3>
    <%= f.fields_for("party_answers_attributes[]", f.object.party_answers.build) do |t| %>
  　  <div class="field">
        <%= t.select :answer_content, {"賛成" => 1, "やや賛成" => 2, "中立" => 3, "やや反対" => 4, "反対" => 5}, :selected => @question.party_answers[key][:answer_content] %>
        <%= t.hidden_field :party_id, :value => party[:id] %>
   　</div>
     <% end %> 
   <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h2>Questions</h2>

<% @questions.each do |question| %>

<h2><%= question.question_content %></h2>
<table>

  <tr>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</table>
<% end %>


<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<h2><%= @question.question_content %></h2>
<p><%= image_tag @question.question_img %></p>
<p><%= @question.question_description %></p>
<% @parties.each_with_index do |party, key| %>  
  <h3><%= party[:party_id] %>&nbsp;<%= party[:party_name] %></h3>
  <p><%= party_content_label(@party_answers[key][:answer_content]) %></p>
<% end %>


<%= link_to "質問一覧へ戻る", questions_path %>