config/routes.rb
Politics::Application.routes.draw do
  get "home/index"

  resources :questions
  resources :parties
  resources :machings, :replace_id_with => 'access_token' do
    collection { post "result" }
    resources :answers
  end
  resources :answers
  root :to => 'home#index'
  get "android/new"
  match "/android", :controller => :android, :action => :index
  match "android/post", :controller => :android, :action => :post
  post "android/create", :controller => :android, :action => :create 
end

app/models/party.rb
class Party < ActiveRecord::Base

  has_many :party_answers
  has_many :questions, through: :party_answers
  accepts_nested_attributes_for :questions

  attr_accessible(
    :party_id,
    :party_name,
    :party_img,
    :description
  )


end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  def index
    @parties = Party.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties }
    end

  end


  def show
    @party = Party.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party
      }
    end
  end


  def new
    @party = Party.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /questions/1/edit
  def edit
    @party = Party.find(params[:id])
  end


  def create
    @party = Party.new(params[:party])
    
    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Question was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @party = Party.find(params[:id])
    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @party = Party.find(params[:id])
    @party_answers = @party.party_answers
    @party_answers.destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end



end

app/helpers/party_helper.rb
module PartyHelper
end

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :party_name %><br />
    <%= f.text_field :party_name %>
  </div>

  <% if @party[:party_img].present? %>
    <div class="field">
    <%= image_tag @party[:party_img] %>
    </div>
  <% end %>
     

  <div class="field">
    <%= f.label :party_img %><br />
    <%= f.text_field :party_img %>
  </div>

  <div class="field">
    政党概要<br />
    <%= f.text_area :description, :style => "width:450px;height:100px;" %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<h2>Parties</h2>

<% @parties.each do |party| %>

<table>
<tr>
  <th>
    <%= party.id %>
  </th>
  <td>
    <%= party.party_name %>
  </td>
</tr>
<tr>
  <td><%= link_to 'Show', party %></td>
  <td><%= link_to 'edit', edit_party_path(party) %></td>
  <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
</table>

<% end %>




<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<h2>政党詳細</h2>

<h3><%= @party.party_name %></h3>

<p><%= image_tag @party.party_img %> </p>
<p><%= @party.description %></p>


<%= link_to "政党一覧へ戻る", parties_path %>