config/routes.rb
Politics::Application.routes.draw do
  get "home/index"

  resources :questions
  resources :parties
  resources :machings, :replace_id_with => 'access_token' do
    collection { post "result" }
    resources :answers
  end
  resources :answers
  root :to => 'home#index'
  get "android/new"
  match "/android", :controller => :android, :action => :index
  match "android/post", :controller => :android, :action => :post
  post "android/create", :controller => :android, :action => :create 
end

app/models/maching.rb
# -*- coding: utf-8 -*-
class Maching < ActiveRecord::Base

  include UUIDHelper
  validates_uniqueness_of :access_token
  validates_presence_of :access_token
  after_initialize :set_access_token

  private
  def set_access_token
    self.access_token = self.access_token.blank? ? generate_access_token : self.access_token
  end  


  def generate_access_token
    tmp_token = SecureRandom.urlsafe_base64(7)
    self.class.where(:access_token => tmp_token).blank? ? tmp_token : generate_access_token
  end

  def to_param  # overridden
    access_token
  end
   


  has_many :answers
  accepts_nested_attributes_for :answers

  attr_accessible(
    :cookie_id,
    :gender,
    :age,
    :electoral_zone,
    :policy1,
    :policy2,
    :policy3,
    :uuid,
    :access_token,
    :answers_attributes
  )

  GENDER ={"男性" => 1, "女性" => 2} 
  AGE = { "20代" => 1, "30代" => 2, "40代" => 3, "50代" => 4, "60代" => 5, "それ以上" =>6}
  
  PREFECTURES = {
  "1"   => "北海道",
  "2"   => "青森県",
  "3"   => "岩手県",
  "4"   => "宮城県",
  "5"   => "秋田県",
  "6"   => "山形県",
  "7"   => "福島県",
  "8"   => "茨城県",
  "9"   => "栃木県",
  "10"  => "群馬県",
  "11"  => "埼玉県",
  "12"  => "千葉県",
  "13"  => "東京都",
  "14"  => "神奈川県",
  "15"  => "新潟県",
  "16"  => "富山県",
  "17"  => "石川県",
  "18"  => "福井県",
  "19"  => "山梨県",
  "20"  => "長野県",
  "21"  => "岐阜県",
  "22"  => "静岡県",
  "23"  => "愛知県",
  "24"  => "三重県",
  "25"  => "滋賀県",
  "26"  => "京都府",
  "27"  => "大阪府",
  "28"  => "兵庫県",
  "29"  => "奈良県",
  "30"  => "和歌山県",
  "31"  => "鳥取県",
  "32"  => "島根県",
  "33"  => "岡山県",
  "34"  => "広島県",
  "35"  => "山口県",
  "36"  => "徳島県",
  "37"  => "香川県",
  "38"  => "愛媛県",
  "39"  => "高知県",
  "40"  => "福岡県",
  "41"  => "佐賀県",
  "42"  => "長崎県",
  "43"  => "熊本県",
  "44"  => "大分県",
  "45"  => "宮崎県",
  "46"  => "鹿児島県",
  "47"  => "沖縄県"
  }

  
  
end

app/controllers/machings_controller.rb
# -*- coding: utf-8 -*-
class MachingsController < ApplicationController

  include MachingSum

  def index
    @questions = Question.all
    @machings = Maching.new 
    @answers = Answer.new
    @machings.answers.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answers }
    end
  end

  def show
    @machings = Maching.where(:access_token => params[:access_token]).first
    @user = Maching.find_by_access_token!(params[:access_token])
    @user_data = sum_maching(@user[:id])
    @parties = Party.find(:all)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @maching }
    end
  end

  def new
    @maching = Maching.new
    @answers = Answer.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @maching }
    end
  end

  def create
    @maching = Maching.new(params[:maching])
    @maching.save
    redirect_to :action => "show", :access_token => @maching[:access_token]
  end 
  

end

app/helpers/maching_helper.rb
# -*- coding: utf-8 -*-
module MachingHelper

	def user_data_label(text)
    case text
      when 'Gender'
        p "性別"
      when 'Age'
        p "年齢層"
      when 'Electoral zone'
        p "選挙区"
      when 'Party'
      	p "支持政党"
      when 'Voting'
      	p "投票頻度"
    end

  end
end

app/views/machings/index.html.erb
<h2>投票マッチングページ</h2>


<%= form_for(@machings) do |f| %>
  <% @questions.each do |question| %>
    <h3><%= question.question_content %></h3>	
    <div class="question">
      選択してください<br />
      <button type="button" class="vote-btn btn-primary ansContent1" id="ye-a-q<%= question.id %>">賛成</button>
      <button type="button" class="vote-btn btn-info ansContent2" id="ye-b-q<%= question.id %>">やや賛成</button>
      <button type="button" class="vote-btn btn-success ansContent3" id="ne-c-q<%= question.id %>">中立</button>
      <button type="button" class="vote-btn btn-warning ansContent4" id="no-b-q<%= question.id %>">やや反対</button>
      <button type="button" class="vote-btn btn-danger ansContent5" id="no-a-q<%= question.id %>">反対</button>
    </div>
  
 
   <!-- <input type="hidden" name="answer[answer_content][q<%= question.id %>]" id="question<%= question.id %>" /> -->
   
    <%= f.fields_for :answers do |t| %>
      <%= t.hidden_field :answer_content, :id =>"ans#{question.id}", :class => "sum" %>
      <%= t.hidden_field :question_id, :id=>"ans_questionID#{question.id}", :class => "sum" %>
    <% end %>
  
    <p><span class="answerText<%= question.id %>"></span></p>
  <% end %>



 
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender, Maching::GENDER %>
  </div>


  <div class="field">
    <%= f.label :age %><br />
    <%= f.select :age, Maching::AGE %>
  </div>

  <div class="field">
    <%= f.label :electoral_zone %><br />
    <%= f.select :electoral_zone, Maching::PREFECTURES.map{|zone| [zone[1], zone[0] ]} %>
  </div>


  <h4>興味のある政策を３つ選んでください。</h4>
  <div class="importantPolicy clearfix">
   <ul>
     <li class="btnImportant" id="policy1">金融政策</li>
     <li class="btnImportant" id="policy2">TPP経済協定</li>
     <li class="btnImportant" id="policy3">原子力発電</li>
     <li class="btnImportant" id="policy4">憲法改正</li>
     <li class="btnImportant" id="policy5">公共事業</li>
     <li class="btnImportant" id="policy6">消費税増税</li>
     <li class="btnImportant" id="policy7">集団的自衛権</li>
     <li class="btnImportant" id="policy8">年金制度</li>
     <li class="btnImportant" id="policy9">被災者支援</li>
     <li class="btnImportant" id="policy10">医療制度</li>
   </ul>
  </div>

  <div class="inputChekBox">
   
       <%= check_box 'maching', 'policy', {:id => 'maching_policy1', :class => 'importantCheck'}, '金融政策', false %>
       <%= check_box 'maching', 'policy', {:id => 'maching_policy2', :class => 'importantCheck'}, 'TPP経済協定', false %>
       <%= check_box 'maching', 'policy', {:id => 'maching_policy3', :class => 'importantCheck'}, '原子力発電', false %>
       <%= check_box 'maching', 'policy', {:id => 'maching_policy4', :class => 'importantCheck'}, '憲法改正', false %>
       <%= check_box 'maching', 'policy', {:id => 'maching_policy5', :class => 'importantCheck'}, '公共事業', false %>

       <%= check_box 'maching', 'policy', {:id => 'maching_policy6', :class => 'importantCheck'}, '消費税増税', false %>
       <%= check_box 'maching', 'policy', {:id => 'maching_policy7', :class => 'importantCheck'}, '集団的自衛権', false %>
       <%= check_box 'maching', 'policy', {:id => 'maching_policy8', :class => 'importantCheck'}, '年金制度', false %>
       <%= check_box 'maching', 'policy', {:id => 'maching_policy9', :class => 'importantCheck'}, '被災者支援', false %>
       <%= check_box 'maching', 'policy', {:id => 'maching_policy10', :class => 'importantCheck'}, '医療制度', false %>
    
  </div>

  <p><span class="answerImportant"></span></p>
  <p><span class="completeText"></span></p>
  <input type="hidden" name="maching[cookie_id]" value="<%= UUID.new.generate %>" />
  <%= f.submit :id=>'machingSubmit' %>
<% end %>

app/views/machings/new.html.erb
<h1>投票結果</h1>



<%= link_to 'Back', machings_path %>

app/views/machings/show.html.erb
<h2>あなたが考えに近い政党順位</h2>

<table class="table">
<% @user_data.each_with_index do |value, key| %>
<tr>
  <th style="width:10%;"><%= key + 1 %>位</th>
  <td style="width:80%;"><%= @parties[key].party_name %></td>
  <td style="width:10%;"><%= link_to '政党詳細', {:controller => 'parties', :action => 'show', :id => @parties[key].id} %></td>
</tr>
<% end %>
</table>
<%= link_to "マッチングへ戻る", machings_path %>